-keep class io.github.darriousliu.katex.freetype.LibraryVersion { *; }
-keep class io.github.darriousliu.katex.freetype.Kerning { *; }
-keep class io.github.darriousliu.katex.freetype.FreeTypeAndroid { *; }